version: 2.1

commands:
  default:
    steps:
      - checkout
      - run:
          name: Installing NSIS
          command: |
            sudo bash -c 'echo "deb http://ftp.us.debian.org/debian unstable main contrib non-free" >> /etc/apt/sources.list.d/unstable.list'
            sudo apt-get -y update
            sudo apt-get -y install -t unstable nsis
            npm install
      - run:
          name: Print versions
          command: |
            node --version
            yarn --version
            makensis -VERSION
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installing Dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Linting Source
          command: npm run lint
      - run:
          name: Building Source
          command: npm run build
      - run:
          name: Running Tests
          command: npm test

jobs:
  node-latest:
    docker:
      - image: circleci/node:latest
    steps:
      - default

  node-lts:
    docker:
      - image: circleci/node:lts
    steps:
      - default

workflows:
  node-multi-build:
    jobs:
    - node-latest
    - node-lts
  version: 2
