version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:9.4.0
    steps:
      - checkout
      - run:
          name: Installing NSIS
          command: 'sudo apt-get update; sudo apt-get install nsis'
      - run:
          name: Printing NSIS version
          command: 'makensis -VERSION'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installing npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Running tests
          command: npm test
