version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run: 'sudo apt-get update; sudo apt-get install nsis'
      - run: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths: ./node_modules
      - run: npm test
