version: 2
commands:
  build:
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Installing NSIS
          command: 'sudo apt-get update; sudo apt-get install nsis'
      - run:
          name: Print NSIS version
          command: 'makensis -VERSION'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installing Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Running Linter
          command: npm run lint
      - run:
          name: Running Tests
          command: npm run test

jobs:
  node-latest:
    docker:
      - image: circleci/node:latest
    steps:
      - build
  node-lts:
    docker:
      - image: circleci/node:lts
    steps:
      - build

workflows:
  node-multi-build:
    jobs:
      - node-latest
      - node-lts
