version: 2.1

commands:
  run-tests:
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Installing NSIS
          command: 'sudo apt-get update; sudo apt-get install nsis'
      - run:
          name: Print NSIS version
          command: 'makensis -VERSION'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installing Dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Running Linter
          command: yarn lint
      - run:
          name: Running Tests
          command: yarn test

jobs:
  node-lts:
    docker:
      - image: circleci/node:lts
    steps:
      - run-tests
  node-latest:
    docker:
      - image: circleci/node:latest
    steps:
      - run-tests

workflows:
  node-multi-build:
    jobs:
      - node-lts
      - node-latest
