version: 2

jobs:
  node-latest:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Installing NSIS
          command: 'sudo apt-get update; sudo apt-get install nsis'
      - run:
          name: Print NSIS version
          command: 'makensis -VERSION'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installing Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Running Tests
          command: npm test
  node-lts:
    working_directory: ~/repo
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Installing NSIS
          command: 'sudo apt-get update; sudo apt-get install nsis'
      - run:
          name: Print NSIS version
          command: 'makensis -VERSION'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installing Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Running Tests
          command: npm test

workflows:
  node-multi-build:
    jobs:
    - node-latest
    - node-lts
  version: 2
