name: "Run tests on Deno"

on:
  push:
    paths:
      - ".github/workflows/deno.yml"
      - "src/**"
      - "tests/**"
      - "types/**"
      - "biome.jsonc"
      - "package.json"
      - "pnpm-lock.yaml"
  pull_request:
    paths:
      - ".github/workflows/deno.yml"
      - "src/**"
      - "tests/**"
      - "types/**"
      - "biome.jsonc"
      - "package.json"
      - "pnpm-lock.yaml"
  workflow_dispatch:

jobs:
  default:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 10

      - name: "Install NSIS"
        uses: nsis-dev/setup-nsis@a33839d33d9fb676b90aa455b1a11fb207be059a # v1.1.1

      - name: "Print NSIS version"
        run: makensis -VERSION

      - name: "Print NSIS header info"
        run: makensis -HDRINFO

      - uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        with:
          deno-version: v2.x

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        name: Set up Deno cache
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: "Install dependencies"
        run: deno install

      - name: Lint Source
        run: deno lint --ignore=node_modules **/*.ts

      - name: Run Tests
        run: |
          deno run --allow-all npm:uvu tests/unit -r tsm
          deno run --allow-all npm:uvu tests/integration -r tsm
