name: Publish on JSR

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x

      - uses: actions/cache@v4
        name: Set up Deno cache
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/pnpm-lock.yaml') }}
      - run: |
          deno lint \
            --ignore=node_modules src tests \
            --rules-exclude=no-explicit-any \
            ./*.ts tests/**/*.ts

          deno publish --dry-run
          deno publish
