name: "Run tests on NodeJS"

on:
  push:
    paths:
      - ".github/workflows/nodejs.yml"
      - "src/**"
      - "tests/**"
      - "types/**"
      - "biome.jsonc"
      - "package.json"
      - "pnpm-lock.yaml"
  pull_request:
    paths:
      - ".github/workflows/nodejs.yml"
      - "src/**"
      - "tests/**"
      - "types/**"
      - "biome.jsonc"
      - "package.json"
      - "pnpm-lock.yaml"
  workflow_dispatch:

jobs:
  default:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: ["24"]
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 10

      - name: "Install NSIS"
        uses: nsis-dev/setup-nsis@a33839d33d9fb676b90aa455b1a11fb207be059a # v1.1.1

      - name: "Print NSIS version"
        run: makensis -VERSION

      - name: "Print NSIS header info"
        run: makensis -HDRINFO

      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Get pnpm store directory"
        id: pnpm-cache
        shell: bash
        run: |
          echo "pnpm_store_path=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        name: "Setup pnpm cache"
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_store_path }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: "Install dependencies"
        run: pnpm install --frozen-lockfile --strict-peer-dependencies

      - name: "Lint Source"
        if: matrix.os != 'windows-latest'
        run: pnpm exec biome ci

      - name: "Build Source"
        run: pnpm run --if-present build

      - name: "Run Tests"
        run: pnpm run --if-present test
