name: CI:Wine

on: [push]

jobs:
  default:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: ['12', '14', '16']
        os: [macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Wine (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install wine

    - name: Install Wine (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run:   |
        sudo dpkg --add-architecture i386
        sudo apt-get -y update
        sudo apt-get -y install wine

    - name: Install NSIS
      run: |
        curl -L https://downloads.sourceforge.net/project/nsis/NSIS%203/3.07/nsis-3.07-setup.exe -o /tmp/nsis-$GITHUB_SHA.exe
        wine /tmp/nsis-$GITHUB_SHA.exe /S

    - name: Print NSIS version
      run: wine 'C:/Program Files (x86)/NSIS\makensis.exe' /VERSION

    - name: Print NSIS header info
      run: wine 'C:/Program Files (x86)/NSIS\makensis.exe' /HDRINFO

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install Package Dependencies
      run: npm ci

    - name: Lint Source
      run: npm run lint --if-present

    - name: Build Source
      run: npm run build --if-present

    - name: Run Tests
      run: npm run test:wine --if-present
