name: CI:Wine

on:
  push:
    paths:
    - '.github/**'
    - 'src/**'
    - 'test/**'
    - 'types/**'
    - 'package.json'
    - 'pnpm-lock.yaml'
  pull_request:
      paths:
      - '.github/**'
      - 'src/**'
      - 'test/**'
      - 'types/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
  workflow_dispatch:

jobs:
  default:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: ['14', '16', '18']
        os: [macos-10.15, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Wine (macOS)
      if: matrix.os == 'macos-10.15'
      run: |
        brew update
        brew tap gcenx/wine
        brew install --cask --no-quarantine gcenx/wine/wine-crossover
      env:
        WINEARCH: win32
        WINEPREFIX: ${{ runner.temp }}/.wine32

    - name: Install Wine (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run:   |
        sudo dpkg --add-architecture i386
        sudo apt-get -y update
        sudo apt-get -y install wine-stable
      env:
        WINEARCH: win32
        WINEPREFIX: ${{ runner.temp }}/.wine32

    - name: Install NSIS
      run: |
        curl -L https://downloads.sourceforge.net/project/nsis/NSIS%203/3.09/nsis-3.09-setup.exe -o ${{ runner.temp }}/nsis-setup-$GITHUB_SHA.exe
        wine ${{ runner.temp }}/nsis-setup-$GITHUB_SHA.exe /S
        wine regedit "${GITHUB_WORKSPACE}/.github/nsis.reg"
      env:
        WINEARCH: win32
        WINEDEBUG: -all

    - name: Print NSIS version (macOS)
      if: matrix.os == 'macos-10.15'
      run: wine makensis /VERSION
      env:
        WINEARCH: win32
        WINEDEBUG: -all

    - name: Print NSIS version (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: wine makensis /VERSION
      env:
        WINEARCH: win32
        WINEDEBUG: -all

    - name: Print NSIS header info (macOS)
      if: matrix.os == 'macos-10.15'
      run: wine makensis /HDRINFO
      env:
        WINEARCH: win32
        WINEDEBUG: -all

    - name: Print NSIS header info (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: wine makensis /HDRINFO
      env:
        WINEARCH: win32
        WINEDEBUG: -all

    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 7
        run_install: |
          - recursive: true
          - args: [--frozen-lockfile, --strict-peer-dependencies]

    - name: Lint Source
      run: pnpm --if-present run lint

    - name: Build Source
      run: pnpm --if-present run build

    - name: Run Tests (macOS)
      if: matrix.os == 'macos-10.15'
      run: pnpm run --if-present test:wine
      continue-on-error: true # unreliable, often times out

    - name: Run Tests (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: pnpm run --if-present test:wine
